version: "2"

services:
  minio1:
    image: minio/minio
    volumes:
      - data1:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: s420
      MINIO_SECRET_KEY: xxxxxxxxxxxxxxx
    command: server http://minio{1...4}/export
  minio2:
    image: minio/minio
    volumes:
      - data2:/export
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: s420
      MINIO_SECRET_KEY: xxxxxxxxxxxxxxx
    command: server http://minio{1...4}/export
  minio3:
    image: minio/minio
    volumes:
      - data3:/export
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: s420
      MINIO_SECRET_KEY: xxxxxxxxxxxxxxx
    command: server http://minio{1...4}/export
  minio4:
    image: minio/minio
    volumes:
      - data4:/export
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: s420
      MINIO_SECRET_KEY: xxxxxxxxxxxxxxx
    command: server http://minio{1...4}/export

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
  data2:
  data3:
  data4:
